---
extends: default

rules:
  comments:
    min-spaces-from-content: 1

  comments-indentation: disable

  braces:
    max-spaces-inside: 1
    min-spaces-inside-empty: 1
    max-spaces-inside-empty: 1

  line-length:
    max: 120

  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
