---
- name: Create group for user
  ansible.builtin.group:
    name: "{{ provision_username }}"
    state: present

- name: Create user {{ provision_username }}
  ansible.builtin.user:
    state: present
    name: "{{ provision_username }}"
    group: "{{ provision_username }}"
    groups: sudo
    append: true
    shell: /usr/bin/zsh
    password: "{{ provision_userpass | mandatory | password_hash('sha512') }}"
    update_password: on_create
