---
# Set up git branch name in PS1 through bashrc
- name: Ensure .config exists in home
  ansible.builtin.file:
    dest: "{{ home }}/.config"
    state: directory
    owner: "{{ uid }}"
    group: "{{ gid }}"
    mode: "0755"

- name: Clone kickstart.nvim
  ansible.builtin.git:
    repo: "https://github.com/nvim-lua/kickstart.nvim.git"
    dest: "{{ home }}/.config/nvim"

- name: Run kickstart.nvim setup
  ansible.builtin.command:
    cmd: nvim --headless "+Lazy! sync" +qa
    creates: "{{ home }}/.local/share/nvim/"


- name: Bash
  block:
    - name: Set long bash history
      ansible.builtin.lineinfile:
        path: "{{ home }}/.bashrc"
        regexp: "{{ item.find }}"
        line: "{{ item.line }}"
      loop:
        - { find: "^HISTSIZE=*", line: "HISTSIZE=5000" }
        - { find: "^HISTFILESIZE=*", line: "HISTFILESIZE=10000" }

    - name: Add aliases
      ansible.builtin.copy:
        src: bash/dotbash_aliases
        dest: "{{ home }}/.bash_aliases"
        owner: "{{ uid }}"
        group: "{{ gid }}"
        mode: "0644"

    - name: Git branch in PS1 - helper files
      ansible.builtin.copy:
        src: git/dotgit/
        dest: "{{ home }}/.git/"
        owner: "{{ uid }}"
        group: "{{ gid }}"
        mode: "0644"

    - name: Git branch in PS1 - .bashrc
      ansible.builtin.blockinfile:
        path: "{{ home }}/.bashrc"
        block: |
          # Git stuff
          . "$HOME/.git/git-completion.bash"
          . "$HOME/.git/git-prompt.sh"

          export GIT_PS1_SHOWDIRTYSTATE=1
          export GIT_PS1_SHOWSTASHSTATE=1
          export GIT_PS1_SHOWUNTRACKEDFILES=1
          export GIT_PS1_SHOWUPSTREAM=1
          export PS1="\[\e[01;32m\H \A \[\e[01;34m\]\w\[\e[38;5;204m\]\$(__git_ps1)\n\[\e[01;32m\]>\[\e[00m\] "
          export PS2="\[\e[38;5;204m\]>\[\e[00m\] "

    - name: Set editor to vim
      ansible.builtin.lineinfile:
        path: "{{ home }}/.bashrc"
        regexp: "^export EDITOR=*"
        line: "export EDITOR=vim"


- name: Copy .gitconfig
  ansible.builtin.copy:
    src: git/dotgitconfig
    dest: "{{ home }}/.gitconfig"
    owner: "{{ uid }}"
    group: "{{ gid }}"
    mode: "0644"

- name: Copy .lintr
  ansible.builtin.copy:
    src: R/dotlintr
    dest: "{{ home }}/.lintr"
    owner: "{{ uid }}"
    group: "{{ gid }}"
    mode: "0644"

- name: SSH
  block:
    - name: Ensure .ssh exists
      ansible.builtin.file:
        dest: "{{ home }}/.ssh"
        state: directory
        owner: "{{ uid }}"
        group: "{{ gid }}"
        mode: "0700"

    - name: Copy SSH config
      ansible.builtin.copy:
        src: ssh/config
        dest: "{{ home }}/.ssh/config"
        owner: "{{ uid }}"
        group: "{{ gid }}"
        mode: "0644"

- name: Copy .zshrc
  ansible.builtin.template:
    src: zsh/dotzshrc.j2
    dest: "{{ home }}/.zshrc"
    owner: "{{ uid }}"
    group: "{{ gid }}"
    mode: "0644"
