---
- name: Ensure .config exists in home
  ansible.builtin.file:
    dest: "{{ home }}/.config"
    state: directory
    owner: "{{ uid }}"
    group: "{{ gid }}"
    mode: "0755"

- name: Ensure nvim exists in .config
  ansible.builtin.file:
    dest: "{{ home }}/.config/nvim"
    state: directory
    owner: "{{ uid }}"
    group: "{{ gid }}"
    mode: "0755"

- name: Copy kickstart.nvim dependencies
  ansible.builtin.copy:
    src: kickstart.nvim/lua
    dest: "{{ home }}/.config/nvim/"
    owner: "{{ uid }}"
    group: "{{ gid }}"
    mode: "0755"

- name: Copy init.lua
  ansible.builtin.template:
    src: kickstart.nvim/init.lua.j2
    dest: "{{ home }}/.config/nvim/init.lua"
    owner: "{{ uid }}"
    group: "{{ gid }}"
    mode: "0644"

- name: Run kickstart.nvim setup
  ansible.builtin.command:
    cmd: nvim --headless "+Lazy! sync" +qa
    creates: "{{ home }}/.local/share/nvim/"


- name: Install ohmyzsh
  ansible.builtin.shell:
    # Yoinked from https://github.com/ThePrimeagen/ansible/blob/master/tasks/zsh-setup.yml
    cmd: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > /tmp/oh-my-installer && chmod +x /tmp/oh-my-installer && /tmp/oh-my-installer
    creates: "{{ home }}/.oh-my-zsh"

# Theme is configured in .zshrc
- name: Install Alien theme
  remote_user: "{{ provision_username }}"
  ansible.builtin.git:
    repo: https://github.com/eendroroy/alien.git
    dest: ~/.alien
    accept_hostkey: true
    depth: 1

- name: Check user's shell
  ansible.builtin.command: grep "^jonathan.*zsh.*" /etc/passwd
  register: user_shell
  changed_when: no
  failed_when: user_shell.stderr != ""

- name: Change shell to zsh
  ansible.builtin.expect:
    command: chsh -s "/usr/bin/zsh"
    responses:
      (?i)password: "{{ provision_userpass }}"
  when: user_shell.rc != 0

- name: Copy .zshrc
  ansible.builtin.template:
    src: zsh/.zshrc
    dest: "{{ home }}/.zshrc"
    owner: "{{ uid }}"
    group: "{{ gid }}"
    mode: "0644"



- name: Copy .gitconfig
  ansible.builtin.copy:
    src: git/dotgitconfig
    dest: "{{ home }}/.gitconfig"
    owner: "{{ uid }}"
    group: "{{ gid }}"
    mode: "0644"

- name: Copy .lintr
  ansible.builtin.copy:
    src: R/dotlintr
    dest: "{{ home }}/.lintr"
    owner: "{{ uid }}"
    group: "{{ gid }}"
    mode: "0644"

- name: SSH
  block:
    - name: Ensure .ssh exists
      ansible.builtin.file:
        dest: "{{ home }}/.ssh"
        state: directory
        owner: "{{ uid }}"
        group: "{{ gid }}"
        mode: "0700"

    - name: Copy SSH config
      ansible.builtin.copy:
        src: ssh/config
        dest: "{{ home }}/.ssh/config"
        owner: "{{ uid }}"
        group: "{{ gid }}"
        mode: "0644"

- name: Markdown Lint
  block:
    - name: Copy .mdlrc
      ansible.builtin.copy:
        src: mdlint/.mdlrc
        dest: "{{ home }}/.mdlrc"
        owner: "{{ uid }}"
        group: "{{ gid }}"
        mode: "0644"

    - name: Copy mdlint style files
      ansible.builtin.copy:
        src: mdlint/.mdlstyle.rb
        dest: "{{ home }}/.mdlstyle.rb"
        owner: "{{ uid }}"
        group: "{{ gid }}"
        mode: "0644"

- name: Yamllint config
  block:
    - name: Ensure yamllint config dir exists
      ansible.builtin.file:
        path: "{{ home }}/.config/yamllint"
        state: directory
        owner: "{{ uid }}"
        group: "{{ gid }}"
        mode: "0755"

    - name: Copy yamllint config
      ansible.builtin.copy:
        src: yamllint/config
        dest: "{{ home }}/.config/yamllint/config"
        owner: "{{ uid }}"
        group: "{{ gid }}"
        mode: "0644"
