---
# Set up git branch name in PS1 through bashrc
- name: Bash
  block:
    - name: Set long bash history
      ansible.builtin.lineinfile:
        path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.bashrc"
        regexp: "{{ item.find }}"
        line: "{{ item.line }}"
      loop:
        - { find: "^HISTSIZE=*", line: "HISTSIZE=5000" }
        - { find: "^HISTFILESIZE=*", line: "HISTFILESIZE=10000" }

    - name: Add aliases
      ansible.builtin.copy:
        src: bash/dotbash_aliases
        dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.bash_aliases"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0644


- name: Git
  block:
    - name: Copy .gitconfig
      ansible.builtin.copy:
        src: git/dotgitconfig
        dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.gitconfig"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0644

    - name: Git branch in PS1 - helper files
      ansible.builtin.copy:
        src: git/dotgit/
        dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.git/"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0644

    - name: Git branch in PS1 - .bashrc
      ansible.builtin.blockinfile:
        path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.bashrc"
        block: |
          # Git stuff
          . "$HOME/.git/git-completion.bash"
          . "$HOME/.git/git-prompt.sh"

          export GIT_PS1_SHOWDIRTYSTATE=1
          export GIT_PS1_SHOWSTASHSTATE=1
          export GIT_PS1_SHOWUNTRACKEDFILES=1
          export GIT_PS1_SHOWUPSTREAM=1
          export PS1="\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u:\[\033[01;34m\]\w\[\033[00m\]\[\033[38;5;204m\]\$(__git_ps1)\[\033[00m\]$ "

- name: Copy .lintr
  ansible.builtin.copy:
    src: R/dotlintr
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.lintr"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- name: SSH
  block:
    - name: Ensure .ssh exists
      ansible.builtin.file:
        dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.ssh"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0700

    - name: Copy SSH config
      ansible.builtin.copy:
        src: ssh/config
        dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.ssh/config"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0644

- name: Copy .zshrc
  ansible.builtin.template:
    src: zsh/dotzshrc.j2
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.zshrc"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
