---
- name: Ensure .config exists in home
  ansible.builtin.file:
    dest: "{{ home }}/.config"
    state: directory
    owner: "{{ uid }}"
    group: "{{ gid }}"
    mode: "0755"

- name: Ensure nvim exists in .config
  ansible.builtin.file:
    dest: "{{ home }}/.config/nvim"
    state: directory
    owner: "{{ uid }}"
    group: "{{ gid }}"
    mode: "0755"

- name: Copy nvim config dependencies
  ansible.builtin.copy:
    src: kickstart.nvim/lua
    dest: "{{ home }}/.config/nvim/"
    owner: "{{ uid }}"
    group: "{{ gid }}"
    mode: "0755"

- name: Copy nvim init.lua
  ansible.builtin.template:
    src: kickstart.nvim/init.lua.j2
    dest: "{{ home }}/.config/nvim/init.lua"
    owner: "{{ uid }}"
    group: "{{ gid }}"
    mode: "0644"

- name: Run kickstart.nvim setup
  ansible.builtin.command:
    cmd: nvim --headless "+Lazy! sync" +qa
    creates: "{{ home }}/.local/share/nvim/"


- name: Install ohmyzsh
  ansible.builtin.shell:
    # Yoinked from https://github.com/ThePrimeagen/ansible/blob/master/tasks/zsh-setup.yml
    cmd: "curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > /tmp/oh-my-installer\
      && chmod +x /tmp/oh-my-installer\
      && /tmp/oh-my-installer"
    creates: "{{ home }}/.oh-my-zsh"
  tags:
    # Because I'm piping curl output to a program, lint doesn't recognize that
    - skip_ansible_lint

# Theme is configured in .zshrc
- name: Install Alien theme
  remote_user: "{{ provision_username }}"
  ansible.builtin.git:
    repo: https://github.com/Encephala/alien.git
    dest: "{{ home }}/.alien"
    depth: 1

- name: Check user's shell
  ansible.builtin.command: grep "^jonathan.*zsh.*" /etc/passwd
  register: user_shell
  changed_when: false
  failed_when: user_shell.stderr != ""

# TODO: I don't like that this depends on a python package, not very minimal
- name: Change shell to zsh
  ansible.builtin.expect:
    command: chsh -s "/usr/bin/zsh"
    responses:
      (?i)password: "{{ provision_userpass }}"
  when: user_shell.rc != 0

- name: Copy .zshrc and .zprofile
  ansible.builtin.template:
    src: "zsh/{{ item.src }}"
    dest: "{{ home }}/{{ item.dest }}"
    owner: "{{ uid }}"
    group: "{{ gid }}"
    mode: "0644"
  loop:
    - { src: "dotzshrc", dest: ".zshrc" }
    - { src: "dotzprofile", dest: ".zprofile" }

- name: Install diff-so-fancy
  ansible.builtin.git:
    repo: https://github.com/so-fancy/diff-so-fancy.git
    dest: "{{ home }}/.oh-my-zsh/custom/plugins/diff-so-fancy"
    depth: 1

- name: Install diff-so-fancy helper script
  ansible.builtin.copy:
    src: diff-so-fancy/dsf-filter
    dest: "{{ home }}/.local/bin/"
    owner: "{{ uid }}"
    group: "{{ gid }}"
    mode: "0755"

- name: Copy .gitconfig
  ansible.builtin.copy:
    src: git/dotgitconfig
    dest: "{{ home }}/.gitconfig"
    owner: "{{ uid }}"
    group: "{{ gid }}"
    mode: "0644"

- name: SSH
  block:
    - name: Ensure .ssh exists
      ansible.builtin.file:
        dest: "{{ home }}/.ssh"
        state: directory
        owner: "{{ uid }}"
        group: "{{ gid }}"
        mode: "0700"

    - name: Copy SSH config
      ansible.builtin.copy:
        src: ssh/config
        dest: "{{ home }}/.ssh/config"
        owner: "{{ uid }}"
        group: "{{ gid }}"
        mode: "0644"
