---
- name: Include system setup
  ansible.builtin.import_tasks: system_setup.yml
  tags:
    - system

- name: Include account setup
  ansible.builtin.import_tasks: account_setup.yml
  tags:
    - account

- name: Include ssh setup
  ansible.builtin.import_tasks: ssh_setup.yml
  tags:
    - ssh

- name: Include dotfiles setup
  ansible.builtin.import_tasks: dotfiles.yml
  tags:
    - dotfiles
