---
# Tasks to copy SSH ID, disable password auth and restart sshd
# Must be run as root, requires var `provision_username` to be set
# If provision_copy_private_key is true, also copies the private key

- name: Authorise SSH key
  ansible.posix.authorized_key:
    user: "{{ provision_username }}"
    key: "{{ lookup('ansible.builtin.file', 'ssh/' + filename) }}"
  vars:
    filename: "{{ lookup('ansible.builtin.vars', 'provision_ssh_key_pub') }}"

# authorized_key ensures the directory is created
- name: Copy SSH private key
  ansible.builtin.copy:
    src: "ssh/{{ provision_ssh_key }}"
    dest: "{{ home }}/.ssh/{{ provision_ssh_key }}"
    mode: "0600"
    owner: "{{ uid }}"
    group: "{{ gid }}"
  when: provision_copy_private_key | bool


- name: Harden SSH
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ line.find }}"
    line: "{{ line.replace }}"
    validate: "sshd -T -f %s"
  loop:
    - { find: '^(# *)?PasswordAuthentication (yes|no)', replace: 'PasswordAuthentication no' }
    - { find: '^(# *)?PermitRootLogin (yes|prohibit-password|no)', replace: 'PermitRootLogin no' }
  loop_control:
    loop_var: line
  notify: Restart sshd
  when: not (provision_is_desktop | bool)
