---
# Tasks to copy SSH ID, disable password auth and restart sshd
# Must be run as root, requires var `username` to be set
# If copy_private_key is true, also copies the private key

- name: Authorise SSH key
  ansible.posix.authorized_key:
    user: "{{ username }}"
    key: "{{ lookup('ansible.builtin.file', 'ssh/{{ ssh_key_pub }}') }}"

# authorized_key ensures the directory is created
- name: Copy SSH private key
  ansible.builtin.copy:
    src: "ssh/{{ ssh_key }}"
    dest: "{{ home }}/.ssh/{{ ssh_key }}"
    mode: "0600"
    owner: "{{ uid }}"
    group: "{{ gid }}"
  when: copy_private_key | bool


- name: Harden SSH
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ line.find }}"
    line: "{{ line.replace }}"
    validate: "sshd -T -f %s"
  loop:
    - { find: '^(# *)?PasswordAuthentication (yes|no)', replace: 'PasswordAuthentication no' }
    - { find: '^(# *)?PermitRootLogin (yes|prohibit-password|no)', replace: 'PermitRootLogin no' }
  loop_control:
    loop_var: line
  notify: Restart sshd
