---
- name: Update package repository, upgrade base packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: full

- name: Install packages
  ansible.builtin.apt:
    name:
      - sudo
      - neofetch
      - git
      - curl
      - htop
      - fzf
      - bc
      - gcc # For vim treesitter
      - npm # For many vim LSPs
      - r-base # For R LSP
      - libxml2-dev # For R LSP
      - luarocks # For lua LSP
      - python3-venv # For some vim LSPs
    state: present

# TODO: This doesn't make sense, NVim gets installed globally,
# but relies on rust which gets installed for the {{ username }}
- name: Run rustup
  ansible.builtin.shell: curl https://sh.rustup.rs -sSf | sh -s -- -y
  remote_user: "{{ username }}"

- name: Download Neovim appimage
  ansible.builtin.get_url:
    url: https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
    dest: /tmp/nvim.appimage
    mode: "0755"
    owner: root
    group: root

- name: Install Neovim
  ansible.builtin.command:
    cmd: "{{ item }}"
    creates: /opt/nvim
    chdir: /tmp
  loop:
    - ./nvim.appimage --appimage-extract
    - mv ./squashfs-root /opt/nvim

- name: Add Neovim to PATH
  ansible.builtin.file:
    src: /opt/nvim/AppRun
    dest: /usr/local/bin/nvim
    state: link

- name: Symlink Neovim to vim
  ansible.builtin.file:
    src: /usr/local/bin/nvim
    dest: /usr/local/bin/vim
    state: link

- name: Install QEMU guest agent if VM
  ansible.builtin.apt:
    name:
      - qemu-guest-agent
    state: present
  when: is_vm | bool
  notify: Ensure guest agent enabled

- name: Set hostname for VM if provided
  ansible.builtin.hostname:
    name: "{{ hostname }}"
  when: hostname is defined and is_vm | bool

- name: Set timezone to Amsterdam
  community.general.timezone:
    name: Europe/Amsterdam


- name: Set Unattended upgrades
  ansible.builtin.import_role:
    name: hifis.unattended_upgrades
  vars:
    unattended_dl_limit: 40000

- name: Copy wsl.conf
  ansible.builtin.copy:
    src: wsl/wsl.conf
    dest: /etc/wsl.conf
    mode: "0644"
    owner: root
    group: root
  when: is_wsl

- name: Check if reboot required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Notify reboot required
  ansible.builtin.assert: { that: true, quiet: true }
  changed_when: true
  notify: Reboot required
  when: reboot_required.stat.exists
