---
- name: Install packages
  ansible.builtin.apt:
    name:
      - gcc # For vim treesitter
      - npm # For many vim LSPs
      - unzip # Also for lemminx (XML LSP)
      - luarocks # For lua LSP
      - python3-venv # For some vim LSPs
      - python3-pexpect # For Ansible's expect module
