---
- name: Update package repository, upgrade base packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: full

- name: Install packages
  ansible.builtin.apt:
    name:
      - sudo
      - neofetch
      - neovim
      - git
      - curl
      - htop
      - fzf
      - bc
    state: present

- name: Check if reboot required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Notify reboot required
  ansible.builtin.assert: { that: true, quiet: true }
  changed_when: true
  notify: Reboot required
  when: reboot_required.stat.exists

- name: Install QEMU guest agent if VM
  ansible.builtin.apt:
    name:
      - qemu-guest-agent
    state: present
  when: is_vm | bool
  notify: Ensure guest agent enabled

- name: Set hostname for VM if provided
  ansible.builtin.hostname:
    name: "{{ hostname }}"
  when: hostname is defined and is_vm | bool

- name: Set timezone to Amsterdam
  community.general.timezone:
    name: Europe/Amsterdam


- name: Set Unattended upgrades
  ansible.builtin.import_role:
    name: hifis.unattended_upgrades
  vars:
    unattended_dl_limit: 40000

- name: Copy wsl.conf
  ansible.builtin.copy:
    src: wsl/wsl.conf
    dest: /etc/wsl.conf
    mode: "0644"
    owner: root
    group: root
  when: is_wsl
