---
# vars file for roles/services/postgres
postgresql_global_config_options:
  # Role defaults
  - option: unix_socket_directories
    value: "{{ postgresql_unix_socket_directories | join(',') }}"
  - option: log_directory
    value: "log"
  # Custom
  - option: listen_addresses
    value: "*"

postgresql_databases:
  - name: test

postgresql_users:
  - name: jonathan
    password: "{{ postgresql_db_pass_hash | mandatory }}"


# IP range that all servers are in
ips_servers: "10.0.50.*"
subnet_servers: "10.0.50.0/24"

postgresql_hba_entries:
  # Role default entries
  - { type: local, database: all, user: postgres, auth_method: peer }
  - { type: local, database: all, user: all, auth_method: peer }
  - { type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5 }
  - { type: host, database: all, user: all, address: '::1/128', auth_method: md5 }
  # Custom entries
  - { type: host, database: all, user: all, address: "{{ subnet_servers }}", auth_method: md5 }
