---
# handlers file for provision
- name: Restart sshd
  become: true
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Ensure guest agent enabled
  become: true
  ansible.builtin.service:
    name: qemu-guest-agent
    enabled: true
    state: started

- name: Reboot required
  ansible.builtin.debug:
    msg: "Reboot required for {{ inventory_hostname }}"
  changed_when: true

- name: Manually configure WSL
  ansible.builtin.debug:
    msg: "Make sure to manually configure memory in `%userprofile%\\.wslconf` ({{ inventory_hostname }})"
  changed_when: true
