---
# handlers file for provision
- name: Restart sshd
  become: true
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Ensure guest agent enabled
  become: true
  ansible.builtin.service:
    name: qemu-guest-agent
    enabled: true
    state: started

- name: Reboot required
  ansible.builtin.debug:
    msg: "Reboot required for {{ inventory_hostname }}"
  when: reboot_required.stat.exists
