---
- name: Install desktop
  ansible.builtin.apt:
    name:
      - xfce4
  notify: Reboot

- name: Configure big-store mount
  block:
    # Change to geerlingguy.nfs?
    - name: Ensure NFS dependencies are present
      ansible.builtin.apt:
        name:
          - nfs-common

    - name: Mount big-store for downloads
      ansible.posix.mount:
        path: /mnt/big-store
        src: "{{ hostvars.JFM.ansible_host }}:/big-store/transmission"
        opts: defaults
        fstype: nfs
        state: mounted

    - name: Create symlink to big-store
      ansible.builtin.file:
        src: "/mnt/big-store"
        dest: "{{ ansible_env.HOME }}/{{ big_store_symlink_name }}"
        state: link
        owner: "{{ username }}"
        group: "{{ username }}"


- name: Set up Transmission
  block:
    - name: Install Transmission client
      ansible.builtin.apt:
        name:
          - transmission

    - name: Configure Transmission desktop shortcut
      ansible.builtin.copy:
        remote_src: true
        src: "/usr/share/applications/transmission-gtk.desktop"
        dest: "{{ ansible_env.HOME }}/Desktop/"
        mode: "0755"

    - name: Create Transmission config directory
      ansible.builtin.file:
        state: directory
        path: "{{ ansible_env.HOME }}/.config/transmission/"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: "0755"

    - name: Configure Transmission
      ansible.builtin.template:
        src: settings.j2
        dest: "{{ ansible_env.HOME }}/.config/transmission/settings.json"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: "0600"


- name: Configure Gotify notification
  block:
    - name: Gotify prerequisites
      ansible.builtin.include_role:
        name: gotify_notifier
      vars:
        gotify_token: "{{ gotify_transmission_token }}"

    - name: Copy notification script
      ansible.builtin.template:
        src: script.j2
        dest: "{{ ansible_env.HOME }}/notify"
        mode: "0755"
        owner: "{{ username }}"
        group: "{{ username }}"

- name: Set up firewall
  ansible.builtin.include_role:
    name: geerlingguy.firewall
  vars:
    firewall_allowed_udp_ports:
      - "8080" # Allow RPC over UDP
    firewall_allowed_tcp_ports:
      - "22"
      - "8080" # Allow RPC over TCP
      - "51413" # Allow torrent peer connections
