---
- name: Configure big-store mount
  block:
    - name: Ensure NFS dependencies are present
      ansible.builtin.apt:
        name:
          - nfs-common

    - name: Mount big-store for downloads
      ansible.posix.mount:
        path: /mnt/big-store
        src: "{{ hostvars.jfm.ansible_host }}:/mnt/big-store/transmission-downloads"
        opts: defaults
        fstype: nfs
        state: mounted


- name: Set up Transmission
  block:
    - name: Install Transmission client
      ansible.builtin.apt:
        name:
          - transmission-daemon

    - name: Configure Transmission
      ansible.builtin.template:
        src: settings.j2
        dest: "/var/lib/transmission-daemon/.config/transmission-daemon/settings.json"
        owner: "105"
        group: "112"
        mode: "0600"
      register: transmission_config


    - name: Reload Transmission
      ansible.builtin.service:
        name: transmission-daemon
        state: reloaded
        enabled: yes
      when: transmission_config.changed


- name: Configure Gotify notification
  block:
    - name: Gotify prerequisites
      ansible.builtin.include_role:
        name: gotify_notifier
      vars:
        gotify_token: "{{ gotify_transmission_token }}"

    - name: Copy notification script
      ansible.builtin.template:
        src: script.j2
        dest: "/usr/local/bin/notify"
        mode: "0755"
        owner: root
        group: root

- name: Set up firewall
  block:
    - name: Install iptables
      ansible.builtin.apt:
        name:
          - firewalld

    - name: Enable firewalld
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true

    - name: Allow services through firewalld
      ansible.builtin.firewalld:
        state: enabled
        service: "{{ item }}"
        permanent: true
        immediate: true
      loop:
        - transmission-client
        - nfs
        - nfs3
        - rpc-bind
        - wireguard

    - name: Allow webinterface through firewalld
      ansible.builtin.firewalld:
        state: enabled
        port: "8080/tcp"
        permanent: true
        immediate: true

    - name: Allow Transmission peer ports through firewalld
      ansible.builtin.firewalld:
        state: enabled
        port: "{{ item }}"
        permanent: true
        immediate: true
      loop:
        - 51413/tcp
        - 51413/udp
