deb_architecture: {
    "x86_64": "amd64"
}

# Username of generic user
username: jonathan
ssh_key_path: ~/.ssh/id_rsa.pub

# IP range that all servers are in
ips_servers: "10.0.50.*"
subnet_servers: "10.0.50.0/24"
