galaxy_info:
  author: jonathan
  description: My role to setup a VM to run Transmission
  license: idk
  min_ansible_version: "2.9"

  platforms:
    - name: Debian
      versions:
        - all

dependencies:
  []
