---
galaxy_info:
  author: jonathan
  description: My role to setup a Debian server
  license: idk
  min_ansible_version: "2.9"

  platforms:
    - name: Debian
      versions:
        - all

dependencies:
  - role: geerlingguy.docker
    vars:
      docker_users: "{{ ansible_user_id }}"
      docker_install_compose: false
