---
- name: Update APT cache and upgrade
  hosts: VM, container
  become: true

  tasks:
    - name: Update
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

      when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

    - name: Upgrade
      ansible.builtin.apt:
        upgrade: full

      when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

  # TODO: reboot als nodig
