---
galaxy_info:
  author: jonathan
  description: My role to setup a Debian(-esque) machine
  license: idk
  min_ansible_version: "2.9"

  platforms:
    - name: Debian
      versions:
        - all

dependencies: []
