name: ansible_lint
on:
  [push, workflow_dispatch]

jobs:
  lint:
    name: Ansible lint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Install pip
        run: sudo apt-get install pipx -y

      - name: Install ansible-lint
        run: pipx install --include-deps ansible-lint

      - name: Add pip bin to path
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Run ansible-lint
        run: ansible-lint 2>&1 >> $GITHUB_STEP_SUMMARY
