name: ansible_lint
on:
  [push, workflow_dispatch]

jobs:
  lint:
    name: Ansible lint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Setup ansible-lint
        run: sudo apt-get install ansible-lint -y

      - name: Run ansible-lint
        run: ansible-lint -x yaml[line-length] 2>&1 >> $GITHUB_STEP_SUMMARY
